// File emission for lesson-foundry — generates defense artifacts.
// Pure functions that return { path, content } pairs; caller writes them.

import { clusterName, extractLiteralPattern, escapeRegex } from './route.mjs';

/**
 * Build the grep-gate JSON descriptor for a LINT cluster.
 * Returns { path, content } where path is relative to outDir.
 */
export function buildLintDescriptor(name, findings) {
  const literal = extractLiteralPattern(findings);
  const pattern = literal ? escapeRegex(literal) : clusterName(findings).replace(/-/g, '.*');

  const descriptor = {
    name,
    pattern,
    paths: ['**'],
    message: `lesson-foundry: recurring finding — ${findings[0]?.desc ?? name}`,
  };

  return {
    path: `${name}.lint.json`,
    content: JSON.stringify(descriptor, null, 2) + '\n',
  };
}

/**
 * Build the runnable check script for a LINT cluster.
 * Returns { path, content }.
 */
export function buildCheckScript(name, findings) {
  const literal = extractLiteralPattern(findings);
  const pattern = literal ? escapeRegex(literal) : clusterName(findings).replace(/-/g, '.*');
  const desc = (findings[0]?.desc ?? name).replace(/`/g, "'");

  // The gate must never trip on itself. We exclude VCS/dependency dirs and the
  // generated lessons output directory, and we filter out this script's own file
  // by basename so the gate only ever flags genuine occurrences in source.
  const selfBasename = `check-${name}.mjs`;

  const content = `#!/usr/bin/env node
// Auto-generated by lesson-foundry — do not edit manually.
// Grep gate: ${desc}

import { execSync } from 'node:child_process';
import { resolve, basename } from 'node:path';

const PATTERN = ${JSON.stringify(pattern)};
const ROOT = resolve('.');
// This generated script itself contains PATTERN (above and in its header
// comment). Exclude its own file so the gate never trips on itself.
const SELF = ${JSON.stringify(selfBasename)};

let output = '';
try {
  output = execSync(
    \`grep -rn --include="*.mjs" --include="*.js" --include="*.ts" --include="*.tsx" --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=.aidlc --exclude=\${JSON.stringify(SELF)} -E \${JSON.stringify(PATTERN)} \${JSON.stringify(ROOT)}\`,
    { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
  );
} catch (err) {
  // grep exits 1 when no match — that's the PASS case
  if (err.status === 1) {
    console.log('check-${name}: no matches found — PASS');
    process.exit(0);
  }
  // grep exits 2 on error
  console.error('check-${name}: grep error:', err.message);
  process.exit(2);
}

// Defensive: drop any line that refers to this gate script itself (in case a
// copy lives outside the excluded dirs).
const lines = output
  .split('\\n')
  .filter((l) => l.trim() && basename(l.split(':')[0]) !== SELF);

if (lines.length > 0) {
  console.error('check-${name}: FAIL — pattern found in repo:');
  console.error(lines.join('\\n'));
  process.exit(2);
}

console.log('check-${name}: no matches found — PASS');
process.exit(0);
`;

  return {
    path: `check-${name}.mjs`,
    content,
  };
}

/**
 * Build a SKILL.md stub for a SKILL cluster.
 * Returns { path, content }.
 */
export function buildSkillStub(name, findings, llmRefinement) {
  const count = findings.length;
  const category = findings[0]?.category ?? 'pattern';
  const desc = llmRefinement?.description ?? findings[0]?.desc ?? name;
  const rule = llmRefinement?.rule ?? `Avoid: ${findings[0]?.desc ?? name}`;
  const displayName = llmRefinement?.name ?? name;

  // Collect evidence quotes
  const evidenceQuotes = findings
    .slice(0, 3)
    .map((f) => {
      const parts = [];
      if (f.file) parts.push(`file: ${f.file}`);
      if (f.line) parts.push(`line: ${f.line}`);
      if (f.desc) parts.push(`finding: ${f.desc}`);
      return parts.join(', ');
    })
    .filter(Boolean);

  const evidenceSection = evidenceQuotes.length
    ? evidenceQuotes.map((e) => `- ${e}`).join('\n')
    : '- (no specific file evidence recorded)';

  const content = `---
name: ${displayName}
description: ${desc}
category: ${category}
mined-from: ${count} findings
triggers:
  - ${category}
  - recurring-finding
  - lesson-foundry
---

# ${displayName}

## Rule

${rule}

## Evidence

Mined from ${count} finding${count === 1 ? '' : 's'}:

${evidenceSection}

## Rationale

This skill was auto-generated by lesson-foundry from recurring prosecution findings.
Apply this rule proactively to prevent re-encountering the same issue.
`;

  return {
    path: `${name}.SKILL.md`,
    content,
  };
}

/**
 * Build the interrogation template line for a SPEC-GAP cluster.
 * Returns a markdown line to append to interrogation-template.md.
 */
export function buildSpecGapLine(name, findings) {
  const count = findings.length;
  const desc = findings[0]?.desc ?? name;
  const category = findings[0]?.category ?? 'unknown';
  return `- [ ] **[${category}]** ${desc} *(recurring in ${count} finding${count === 1 ? '' : 's'}, cluster: ${name})*\n`;
}

/**
 * Plan all emissions for a set of clusters.
 * Returns array of { cluster, route, files: [{path, content}], destination }.
 * outDir prefix is applied to paths.
 * llmRefinements: Map<clusterIndex, {name, description, rule}>
 */
export function planEmissions(clusters, allFindings, outDir, llmRefinements = new Map()) {
  const interrogationLines = [];
  const plan = [];

  for (const [idx, cluster] of clusters.entries()) {
    const findings = cluster.indices.map((i) => allFindings[i]);
    const route = cluster.route;
    const name = cluster.name;
    const refinement = llmRefinements.get(idx) ?? null;
    const files = [];

    if (route === 'lint') {
      files.push(buildLintDescriptor(name, findings));
      files.push(buildCheckScript(name, findings));
    } else if (route === 'skill') {
      files.push(buildSkillStub(name, findings, refinement));
    } else {
      // spec-gap — collect lines for interrogation-template.md
      interrogationLines.push(buildSpecGapLine(name, findings));
    }

    // Apply outDir prefix
    const prefixedFiles = files.map((f) => ({
      ...f,
      path: `${outDir}/${f.path}`,
    }));

    plan.push({
      cluster,
      route,
      files: prefixedFiles,
      destination:
        route === 'lint'
          ? `${outDir}/${name}.lint.json + ${outDir}/check-${name}.mjs`
          : route === 'skill'
            ? `${outDir}/${name}.SKILL.md`
            : `${outDir}/interrogation-template.md`,
    });
  }

  // Merge spec-gap lines into interrogation-template.md
  if (interrogationLines.length > 0) {
    const templatePath = `${outDir}/interrogation-template.md`;
    plan
      .filter((p) => p.route === 'spec-gap')
      .forEach((p) => {
        // All spec-gap entries share the same interrogation template file
        p.interrogationPath = templatePath;
      });

    // Add interrogation template as a synthetic "cluster" file entry
    plan.push({
      cluster: null,
      route: 'spec-gap-template',
      files: [
        {
          path: templatePath,
          content:
            `# Interrogation Template\n\n` +
            `Auto-generated by lesson-foundry. Answer these questions in your spec (P1).\n\n` +
            interrogationLines.join(''),
          append: true,
        },
      ],
      destination: templatePath,
    });
  }

  return plan;
}
