import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { writeReproArtifact } from '../lib/record.mjs';

describe('record: writeReproArtifact', () => {
  let tmpDir;

  before(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'gate-fuzzing-record-test-'));
  });

  after(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('writes repro artifact JSON and test scaffold to proper locations', () => {
    const defeat = {
      id: 'test-id',
      target: 'test-target',
      claimKind: 'test-claim',
      strategy: 'test-strategy',
      diff: 'test-diff',
      witnessProposal: { cmd: 'echo', args: ['hi'] },
      verdict: { witnessSource: 'test-source' }
    };

    const reproPath = writeReproArtifact(defeat, tmpDir);

    // Check JSON artifact
    assert.ok(existsSync(reproPath), 'repro artifact should exist');
    assert.ok(reproPath.includes('.adlc/gate-defeats/test-id.json'));

    const content = JSON.parse(readFileSync(reproPath, 'utf8'));
    assert.equal(content.id, 'test-id');
    assert.equal(content.target, 'test-target');
    assert.ok(content.redTestScaffold.includes('// RED test scaffold — gate-fuzzing found bypass: test-id'));

    // Check that TODO is GONE from scaffold
    assert.ok(!content.redTestScaffold.includes('// TODO: Move this to packages/test-target/test/bypass-test-id.test.mjs'));
    assert.ok(content.redTestScaffold.includes('// This test was auto-generated by gate-fuzzing.'));

    // Check that the scaffold was also written to packages/test-target/test/bypass-test-id.test.mjs
    const scaffoldPath = join(tmpDir, 'packages', 'test-target', 'test', 'bypass-test-id.test.mjs');
    assert.ok(existsSync(scaffoldPath), 'test scaffold file should exist in target package');

    const scaffoldContent = readFileSync(scaffoldPath, 'utf8');
    assert.equal(scaffoldContent, content.redTestScaffold);
  });

  test('handles missing defeat.id by generating a timestamp-based ID and using it consistently', () => {
    const defeat = {
      target: 'no-id-target',
      claimKind: 'test-claim',
      strategy: 'test-strategy',
      diff: 'test-diff',
      witnessProposal: { cmd: 'echo', args: ['hi'] }
    };

    const reproPath = writeReproArtifact(defeat, tmpDir);
    const idMatch = reproPath.match(/cand-(\d+)\.json$/);
    assert.ok(idMatch, 'repro path should have timestamp ID');
    const id = `cand-${idMatch[1]}`;

    const artifactContent = JSON.parse(readFileSync(reproPath, 'utf8'));
    assert.equal(artifactContent.id, id);
    assert.ok(artifactContent.redTestScaffold.includes(`// RED test scaffold — gate-fuzzing found bypass: ${id}`), 'scaffold should include the generated ID');

    const scaffoldPath = join(tmpDir, 'packages', 'no-id-target', 'test', `bypass-${id}.test.mjs`);
    assert.ok(existsSync(scaffoldPath), 'scaffold file should exist with generated ID');

    const scaffoldContent = readFileSync(scaffoldPath, 'utf8');
    assert.ok(scaffoldContent.includes(`// RED test scaffold — gate-fuzzing found bypass: ${id}`));
  });
});
