import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { writeReproArtifact } from '../lib/record.mjs';

// Artifact names are derived from the harness-computed dedup hash, never from
// the model-supplied `id` (issue #643). record-paths.test.mjs pins the
// adversarial cases; this file pins the happy path.
const HASH = '0123456789abcdef'.repeat(4);
const ID = HASH.slice(0, 16);

describe('record: writeReproArtifact', () => {
  let tmpDir;

  before(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'gate-fuzzing-record-test-'));
  });

  after(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  test('writes repro artifact JSON and test scaffold at hash-derived locations', () => {
    const defeat = {
      id: 'test-id',
      target: 'test-target',
      claimKind: 'test-claim',
      strategy: 'test-strategy',
      diff: 'test-diff',
      witnessProposal: { cmd: 'echo', args: ['hi'] },
      verdict: { witnessSource: 'test-source' },
      hash: HASH,
    };

    const reproPath = writeReproArtifact(defeat, tmpDir);

    // Check JSON artifact
    assert.ok(existsSync(reproPath), 'repro artifact should exist');
    assert.equal(reproPath, join(tmpDir, '.adlc', 'gate-defeats', `${ID}.json`));

    const raw = readFileSync(reproPath, 'utf8');
    const content = JSON.parse(raw);
    // The artifact is committed and diffed by operators: pin its 2-space layout.
    assert.equal(raw, JSON.stringify(content, null, 2));
    assert.equal(content.id, ID);
    assert.equal(content.candidateId, 'test-id', 'the model id survives as data only');
    assert.equal(content.target, 'test-target');
    assert.equal(content.witnessSource, 'test-source');
    assert.ok(content.redTestScaffold.includes(`// RED test scaffold — gate-fuzzing found bypass: ${ID}`));
    assert.ok(content.redTestScaffold.includes('// This test was auto-generated by gate-fuzzing.'));

    // The scaffold was also written to packages/test-target/test/bypass-<id>.test.mjs
    const scaffoldPath = join(tmpDir, 'packages', 'test-target', 'test', `bypass-${ID}.test.mjs`);
    assert.ok(existsSync(scaffoldPath), 'test scaffold file should exist in target package');

    const scaffoldContent = readFileSync(scaffoldPath, 'utf8');
    assert.equal(scaffoldContent, content.redTestScaffold);
  });

  test('handles a missing hash by generating a timestamp-based ID and using it consistently', () => {
    const defeat = {
      target: 'no-id-target',
      claimKind: 'test-claim',
      strategy: 'test-strategy',
      diff: 'test-diff',
      witnessProposal: { cmd: 'echo', args: ['hi'] },
    };

    const reproPath = writeReproArtifact(defeat, tmpDir);
    const idMatch = reproPath.match(/cand-(\d+)\.json$/);
    assert.ok(idMatch, 'repro path should have timestamp ID');
    const id = `cand-${idMatch[1]}`;

    const artifactContent = JSON.parse(readFileSync(reproPath, 'utf8'));
    assert.equal(artifactContent.id, id);
    assert.equal(artifactContent.candidateId, null);
    assert.ok(artifactContent.redTestScaffold.includes(`// RED test scaffold — gate-fuzzing found bypass: ${id}`), 'scaffold should include the generated ID');

    const scaffoldPath = join(tmpDir, 'packages', 'no-id-target', 'test', `bypass-${id}.test.mjs`);
    assert.ok(existsSync(scaffoldPath), 'scaffold file should exist with generated ID');

    const scaffoldContent = readFileSync(scaffoldPath, 'utf8');
    assert.ok(scaffoldContent.includes(`// RED test scaffold — gate-fuzzing found bypass: ${id}`));
  });
});
