// AC 52 / 56 / 75 / 157 / 162 — the dependency-diff check, the canonical
// lockfile comparison (fixture generated by a REAL offline
// `npm install --package-lock-only`), the exact-name guard, and the two
// sanitized host-side installs (worker-deps online-capable, gate-deps offline).

import { test } from './helpers/node-test.mjs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { dependencyDiffCheck, comparePackageJson, buildWorkerDeps, installGateDeps, sanitizedNpmArgv, checkIgnoredFiles, PINNED_REGISTRY } from '../lib/deps.mjs';
import { compareLockfiles, parseLockfile } from '../lib/lockfile.mjs';
import { ALLOWED_WORKSPACE_DEPS } from '../lib/config.mjs';
import { withMutation } from '../lib/mutations.mjs';
import { makeCtx, REAL_NPM } from './helpers/gates-ctx.mjs';
import { makeRepo, addIssueWorktree, writeFiles, commitAll, git, scratch } from './helpers/gates-fixture.mjs';

const ISSUE = 7;
const ALLOWED = [...ALLOWED_WORKSPACE_DEPS];
const pkg = (name, extra = {}) => JSON.stringify({ name, version: '1.11.0', type: 'module', scripts: { test: 'node --test test/*.test.mjs' }, ...extra }, null, 2) + '\n';
const WORKSPACE = {
  'package.json': JSON.stringify({ name: 'fixture', version: '1.11.0', private: true, workspaces: ['packages/*'] }, null, 2) + '\n',
  'packages/core/package.json': pkg('@adlc/core'), 'packages/tickets/package.json': pkg('@adlc/tickets'),
  'packages/fleet/package.json': pkg('@adlc/fleet', { dependencies: { '@adlc/core': '1.11.0' } }), 'packages/spec-lint/package.json': pkg('@adlc/spec-lint'),
  'packages/foo/package.json': pkg('@adlc/foo'), 'packages/foo/lib/x.mjs': 'export const x = 1;\n', '.gitignore': 'node_modules/\n',
};

/** The REAL `npm install --package-lock-only --ignore-scripts --offline` over a workspace; { text } or { error }. */
function generateLock(dir) {
  const home = join(dir, '.npm-home'); mkdirSync(home, { recursive: true });
  const rc = join(dir, '.npmrc-generated'); writeFileSync(rc, `registry=${PINNED_REGISTRY}\n`);
  try {
    execFileSync(REAL_NPM, ['install', '--package-lock-only', '--ignore-scripts', '--offline', '--no-audit', '--no-fund', '--userconfig', rc, '--globalconfig', '/dev/null'],
      { cwd: dir, env: { PATH: process.env.PATH, HOME: home, npm_config_cache: join(dir, '.npm-cache') }, stdio: 'pipe', timeout: 120_000 });
    const text = readFileSync(join(dir, 'package-lock.json'), 'utf8');
    rmSync(home, { recursive: true, force: true }); rmSync(rc, { force: true }); rmSync(join(dir, '.npm-cache'), { recursive: true, force: true });
    return { text };
  } catch (e) { return { error: `${e.message}\n${e.stderr ?? ''}`.trim() }; }
}

const LOCKS = (() => {
  const dir = scratch('ap-lock-');
  try {
    writeFiles(dir, WORKSPACE);
    const base = generateLock(dir);
    if (base.error) return { error: base.error };
    writeFiles(dir, { 'packages/autopilot/package.json': pkg('@adlc/autopilot', { dependencies: { '@adlc/core': '1.11.0', '@adlc/fleet': '1.11.0', '@adlc/tickets': '1.11.0' } }) });
    const head = generateLock(dir);
    return head.error ? { error: head.error } : { base: base.text, head: head.text };
  } finally { rmSync(dir, { recursive: true, force: true }); }
})();
// The lockfile fixture is MANDATORY: a failed generation FAILS AC56 and the seam check
// (never a skip — a silent skip would pass the suite without testing AC56; codex T1 r8).
const lockError = LOCKS.error ? `npm cannot generate the lockfile offline — ${LOCKS.error.split('\n')[0]}` : null;
if (lockError) console.error(`deps.test.mjs: ${lockError} (AC56 FAILS: the fixture is mandatory)`);

function fixture(extraFiles = {}) {
  const { root, baseOid } = makeRepo({ files: { ...WORKSPACE, ...(LOCKS.base ? { 'package-lock.json': LOCKS.base } : {}), ...extraFiles } });
  const npmCalls = []; let npmStatus = 0;
  const ctx = makeCtx({ repoRoot: root, baseOid, pinned: { npm: '/fake/npm' }, handlers: { '/fake/npm': (args, { cwd, env }) => { npmCalls.push({ args, cwd, env }); return { status: npmStatus }; } } });
  const wt = addIssueWorktree(root, ctx.paths.issueWorktree(ISSUE), ISSUE, baseOid);
  const commit = (files) => { git(wt, ['reset', '-q', '--hard', baseOid]); writeFiles(wt, files); return commitAll(wt, 'worker'); };
  const check = async (files) => dependencyDiffCheck({ ctx, issue: ISSUE, baseOid, head: commit(files), allowed: ALLOWED });
  return { root, baseOid, ctx, wt, commit, check, npmCalls, setNpmStatus: (s) => { npmStatus = s; }, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

export async function ac52_dependencyDiffCheck() {
  const f = fixture();
  try {
    assert.equal((await f.check({ 'packages/foo/package.json': pkg('@adlc/foo', { dependencies: { 'left-pad': '^1.3.0' } }) })).code, 'third-party-dep');
    assert.equal((await f.check({ 'packages/foo/package.json': pkg('@adlc/foo', { dependencies: { '@adlc/core': '*' } }) })).ok, true, 'adding @adlc/core passes');
    assert.equal((await f.check({ 'packages/foo/package.json': pkg('@adlc/foo', { scripts: { test: 'true' } }) })).code, 'third-party-dep', 'a changed scripts.test');
    assert.equal((await f.check({ 'packages/foo/package.json': pkg('@adlc/foo', { devDependencies: { '@adlc/spec-lint': '*' } }) })).code, 'third-party-dep');
    assert.equal((await f.check({ 'packages/foo/lib/x.mjs': 'export const x = 2;\n' })).ok, true, 'no manifest in the diff → ok');
    f.commit({ 'packages/foo/lib/x.mjs': 'export const x = 3;\n' });
    mkdirSync(join(f.wt, 'node_modules'), { recursive: true }); writeFileSync(join(f.wt, 'node_modules', 'x'), '');
    assert.equal((await checkIgnoredFiles({ ctx: f.ctx, issue: ISSUE })).ok, true, 'node_modules/ is an expected ignored path');
    writeFileSync(join(f.wt, '.gitignore'), 'node_modules/\nplanted.log\n'); writeFileSync(join(f.wt, 'planted.log'), 'x');
    const drift = await checkIgnoredFiles({ ctx: f.ctx, issue: ISSUE });
    assert.equal(drift.code, 'ignored-file-drift'); assert.deepEqual(drift.paths, ['planted.log']);
  } finally { f.cleanup(); }
}
test('AC52: left-pad → third-party-dep, @adlc/core passes, a changed scripts.test fails, an unexpected ignored file in ISSUE_WT → ignored-file-drift', ac52_dependencyDiffCheck);

export async function ac56_lockfileCanonical() {
  assert.equal(lockError, null, lockError ?? '');
  const base = parseLockfile(LOCKS.base); const head = parseLockfile(LOCKS.head);
  assert.ok(base && head, 'both real lockfiles parse');
  const mutate = (fn) => { const doc = JSON.parse(LOCKS.base); fn(doc.packages); return doc; };
  assert.equal(compareLockfiles(base, mutate((p) => { p['node_modules/left-pad'] = { version: '1.3.0', resolved: 'https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz', integrity: 'sha512-x' }; }), { allowed: ALLOWED }).code, 'lockfile-drift', 'a registry entry added');
  assert.equal(compareLockfiles(base, mutate((p) => { p['node_modules/@adlc/foo'].resolved = 'https://registry.npmjs.org/@adlc/foo/-/foo-1.11.0.tgz'; }), { allowed: ALLOWED }).code, 'lockfile-drift', 'resolved changed');
  assert.equal(compareLockfiles(base, mutate((p) => { p['node_modules/@adlc/foo'].integrity = 'sha512-forged'; }), { allowed: ALLOWED }).code, 'lockfile-drift', 'integrity changed');
  assert.equal(compareLockfiles(base, mutate((p) => { delete p['node_modules/@adlc/spec-lint']; }), { allowed: ALLOWED }).code, 'lockfile-drift', 'entry removed');
  const linked = mutate((p) => { p['packages/autopilot'] = { name: '@adlc/autopilot', version: '1.11.0' }; p['node_modules/@adlc/autopilot'] = { resolved: 'packages/autopilot', link: true }; });
  assert.equal(compareLockfiles(base, linked, { allowed: ALLOWED }).ok, true, 'a workspace + its link entry pass');
  const real = compareLockfiles(base, head, { allowed: ALLOWED });
  assert.equal(real.ok, true, `the COMPLETE real npm lockfile for adding packages/autopilot passes: ${real.detail}`);
  assert.ok(head.packages['node_modules/@adlc/autopilot']?.link === true && head.packages['packages/autopilot'], 'npm wrote the workspace link the check admits');
  const argv = sanitizedNpmArgv({ npm: REAL_NPM, userconfig: '/rc', offline: false });
  for (const flag of ['--ignore-scripts', '--no-audit', '--no-fund']) assert.ok(argv.includes(flag), flag);
}
test('AC56: registry additions, a changed resolved/integrity or a removed entry → lockfile-drift; a hand-built AND the real npm-generated packages/autopilot workspace link pass; npm ci carries --ignore-scripts --no-audit --no-fund', ac56_lockfileCanonical);

export async function ac75_exactNameGuard() {
  const base = JSON.parse(pkg('@adlc/foo'));
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/spec-lint': '*' } })), { allowed: ALLOWED }).code, 'third-party-dep', '@adlc/spec-lint is a published workspace outside the allowed set');
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/core': '*' } })), { allowed: ALLOWED }).ok, true);
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/core': 'workspace:*' } })), { allowed: ALLOWED }).ok, true);
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/core': '1.11.0' } })), { allowed: ALLOWED, lockstepVersion: '1.11.0' }).ok, true, 'the lockstep version');
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/core': '^1.0.0' } })), { allowed: ALLOWED }).code, 'third-party-dep', 'a non-workspace range');
  assert.equal(comparePackageJson(base, JSON.parse(pkg('@adlc/foo', { dependencies: { '@adlc/core': 'file:../core' } })), { allowed: ALLOWED }).code, 'npm-config-drift', 'a file: spec');
  const lock = { lockfileVersion: 3, packages: { '': {}, 'packages/core': { name: '@adlc/core', version: '1.11.0' } } };
  const registry = { lockfileVersion: 3, packages: { ...lock.packages, 'node_modules/@adlc/core': { version: '1.11.0', resolved: 'https://registry.npmjs.org/@adlc/core/-/core-1.11.0.tgz', integrity: 'sha512-x' } } };
  assert.equal(compareLockfiles(lock, registry, { allowed: ALLOWED }).code, 'lockfile-drift', 'node_modules/@adlc/core with a registry resolved URL');
  const link = { lockfileVersion: 3, packages: { ...lock.packages, 'node_modules/@adlc/core': { resolved: 'packages/core', link: true } } };
  assert.equal(compareLockfiles(lock, link, { allowed: ALLOWED }).ok, true, 'the workspace link form passes');
  // A link-ONLY change on an entry present in BOTH base and head — a SHARED-entry comparison
  // (checkSharedEntry/COMPARED_FIELDS), not the added-entry path `link` above exercises
  // (2026-08-31: my first attempt at this test put the key only in head, so it never reached
  // COMPARED_FIELDS at all — the mutant survived a "passing" test).
  const linkedBase = { lockfileVersion: 3, packages: { ...lock.packages, 'node_modules/@adlc/core': { resolved: 'packages/core', link: true } } };
  const linkedHeadUnlinked = { lockfileVersion: 3, packages: { ...lock.packages, 'node_modules/@adlc/core': { resolved: 'packages/core', link: false } } };
  assert.equal(compareLockfiles(linkedBase, linkedHeadUnlinked, { allowed: ALLOWED }).code, 'lockfile-drift', 'a link field flip on a SHARED entry is drift');
  assert.equal(lockError, null, lockError ?? '');
  {
    const f = fixture();
    try {
      const r = await f.check({ 'packages/foo/package.json': pkg('@adlc/foo', { dependencies: { '@adlc/spec-lint': '*' } }) });
      assert.equal(r.code, 'third-party-dep'); assert.match(r.detail, /packages\/foo\/package\.json/);
    } finally { f.cleanup(); }
  }
}
test('AC75: adding @adlc/spec-lint → third-party-dep, @adlc/core as a workspace link passes, a lockfile node_modules/@adlc/core with a registry resolved URL → lockfile-drift', ac75_exactNameGuard);

function bareMirror(root, dest, branch) { git(root, ['clone', '-q', '--bare', '--single-branch', '--branch', branch, root, dest]); return dest; }

export async function ac157_gateInstallSanitized() {
  const f = fixture();
  try {
    const attestedHead = f.commit({ 'packages/foo/lib/x.mjs': 'export const x = 9;\n' });
    mkdirSync(f.ctx.paths.runDir(ISSUE), { recursive: true });
    bareMirror(f.root, f.ctx.paths.gateMirror(ISSUE), `adlc/autopilot/issue-${ISSUE}`);
    for (const files of [{ '.npmrc': 'registry=https://evil.example/\n' }, { 'packages/foo/package.json': pkg('@adlc/foo', { overrides: { 'left-pad': '1.0.0' } }) }, { 'packages/foo/package.json': pkg('@adlc/foo', { dependencies: { '@adlc/core': 'file:../core' } }) }]) {
      assert.equal((await f.check(files)).code, 'npm-config-drift', JSON.stringify(files));
    }
    assert.equal(f.npmCalls.length, 0, 'no install spawn follows an npm-config-drift');
    const nm = await installGateDeps({ ctx: f.ctx, issue: ISSUE, attestedHead });
    assert.equal(nm, join(f.ctx.paths.gateDeps(ISSUE), 'node_modules'));
    assert.equal(git(f.ctx.paths.gateDeps(ISSUE), ['rev-parse', 'HEAD']), attestedHead, 'gate-deps is a clone at attestedHead');
    const spawn = f.ctx.recorder.find((s) => s.argv[0] === '/fake/npm');
    assert.equal(spawn.cwd, f.ctx.paths.gateDeps(ISSUE)); assert.ok(!spawn.argv.includes('bwrap') && !spawn.argv[0].endsWith('bwrap'), 'runs on the host');
    assert.ok(spawn.argv.includes('--offline'), '--offline');
    const rc = spawn.argv[spawn.argv.indexOf('--userconfig') + 1];
    assert.ok(rc.startsWith(f.ctx.paths.runDir(ISSUE))); assert.equal(readFileSync(rc, 'utf8'), `registry=${PINNED_REGISTRY}\n`, 'the generated userconfig pins the registry and nothing else');
    assert.equal(spawn.argv[spawn.argv.indexOf('--globalconfig') + 1], '/dev/null');
    assert.ok(spawn.env.HOME.startsWith(f.ctx.paths.runDir(ISSUE)) && readdirSync(spawn.env.HOME).length === 0, 'HOME is an empty private directory');
    const npmVars = Object.keys(spawn.env).filter((k) => /^npm_config_/i.test(k));
    assert.deepEqual(npmVars, ['npm_config_cache']); assert.equal(spawn.env.npm_config_cache, f.ctx.paths.npmCache(ISSUE));
    assert.equal(spawn.env.ADLC_MANIFEST_KEY, undefined);
    const gitIdx = f.ctx.recorder.findIndex((s) => s.argv.includes('clone') && s.argv.includes(f.ctx.paths.gateDeps(ISSUE)));
    assert.ok(gitIdx !== -1 && gitIdx < f.ctx.recorder.indexOf(spawn), 'the clone precedes the install');
    f.setNpmStatus(1);
    await assert.rejects(() => installGateDeps({ ctx: f.ctx, issue: ISSUE, attestedHead }), (e) => e.code === 'gate-deps-missing', 'a cache miss → gate-deps-missing');
  } finally { f.cleanup(); }
}
test('AC157: .npmrc / overrides / file: → npm-config-drift with no install; the gate install has cwd gate-deps, --offline, the generated userconfig, --globalconfig /dev/null, an empty HOME and only npm_config_cache; a cache miss → gate-deps-missing', ac157_gateInstallSanitized);

export async function ac162_workerDepsBuilt() {
  const f = fixture();
  try {
    f.commit({ 'packages/foo/lib/x.mjs': 'export const x = 5;\n' });
    mkdirSync(f.ctx.paths.runDir(ISSUE), { recursive: true });
    bareMirror(f.root, f.ctx.paths.mirror(ISSUE), `adlc/autopilot/issue-${ISSUE}`);
    // The retry shape: the worker worktree carries a worker-written .npmrc and a rewritten package.json.
    writeFiles(f.wt, { '.npmrc': 'registry=https://evil.example/\n', 'package.json': JSON.stringify({ name: 'rewritten', version: '9.9.9', scripts: { preinstall: 'curl evil' } }) });
    const nm = await buildWorkerDeps({ ctx: f.ctx, issue: ISSUE, baseOid: f.baseOid });
    assert.equal(nm, join(f.ctx.paths.workerDeps(ISSUE), 'node_modules'));
    assert.equal(git(f.ctx.paths.workerDeps(ISSUE), ['rev-parse', 'HEAD']), f.baseOid, 'worker-deps is a clone at BASE_OID');
    assert.ok(!existsSync(join(f.ctx.paths.workerDeps(ISSUE), '.npmrc')), "the worker's .npmrc never reaches the clone");
    const npm = f.ctx.recorder.filter((s) => s.argv[0] === '/fake/npm');
    assert.equal(npm.length, 1, 'exactly one npm spawn');
    assert.equal(npm[0].cwd, f.ctx.paths.workerDeps(ISSUE)); assert.ok(!npm[0].cwd.startsWith(f.wt), 'never under the worker worktree');
    assert.deepEqual(npm[0].argv.slice(1, 6), ['ci', '--ignore-scripts', '--no-audit', '--no-fund', '--userconfig']); assert.ok(!npm[0].argv.includes('--offline'), 'the one registry-capable install');
    assert.ok(readdirSync(npm[0].env.HOME).length === 0 && npm[0].env.HOME !== f.ctx.env.home, 'empty private HOME');
    assert.deepEqual(Object.keys(npm[0].env).filter((k) => /npm_config/i.test(k)), ['npm_config_cache']);
    f.setNpmStatus(2);
    await assert.rejects(() => buildWorkerDeps({ ctx: f.ctx, issue: ISSUE, baseOid: f.baseOid }), (e) => e.code === 'init-failed' && e.exitCode === 1);
  } finally { f.cleanup(); }
}
test('AC162: worker-deps is a clone at BASE_OID from the mirror with the ONE sanitized registry-capable npm ci (no --offline, never under the worker worktree even on a retry with a worker-written .npmrc); a failed build → init-failed', ac162_workerDepsBuilt);

test('seam check: the deps tests fail under their registered seams', async () => {
  assert.equal(lockError, null, lockError ?? '');
  for (const [seam, fn] of [['deps.ignoreScripts', ac52_dependencyDiffCheck], ['lockfile.ignoreResolved', ac56_lockfileCanonical], ['deps.allowAnyDep', ac75_exactNameGuard], ['deps.allowOnlineGate', ac157_gateInstallSanitized], ['deps.useOperatorHome', ac162_workerDepsBuilt]]) {
    await assert.rejects(() => withMutation(seam, fn), `${fn.name} must fail under ${seam}`);
  }
});

import { readFileSync as readPkg } from 'node:fs';
import { join as joinPkg, dirname as dirnamePkg } from 'node:path';
import { fileURLToPath as toPath } from 'node:url';
import { packageDependencyDiscipline } from '../lib/deps.mjs';

export function ac15_dependencyDiscipline() {
  const pkg = JSON.parse(readPkg(joinPkg(dirnamePkg(toPath(import.meta.url)), '..', 'package.json'), 'utf8'));
  const r = packageDependencyDiscipline(pkg);
  assert.deepEqual(r.problems, [], 'every dependency is @adlc/ and devDependencies is absent or empty');
  assert.equal(r.ok, true);
  assert.ok(Object.keys(pkg.dependencies).length >= 3, 'the package depends on the workspace (core, fleet, tickets)');
  assert.equal(packageDependencyDiscipline({ dependencies: { lodash: '1' } }).ok, false, 'a third-party dependency is a problem');
  assert.equal(packageDependencyDiscipline({ dependencies: {}, devDependencies: { x: '1' } }).ok, false, 'devDependencies are a problem');
}
test('AC15: every key of packages/autopilot/package.json dependencies starts with @adlc/ and devDependencies is absent or empty', ac15_dependencyDiscipline);
