// gate-fuzzing/lib/record.mjs
// Defeat recording: repro artifacts + cluster findings (§4).
// Only writes with --record flag. Default is dry-run.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { appendEntry } from '@adlc/core';

const ADLC_DIR = '.adlc';
const GATE_DEFEATS_DIR = join(ADLC_DIR, 'gate-defeats');

/**
 * Write a defeat repro artifact to .adlc/gate-defeats/<id>.json (§4.3).
 * Includes: id, target, claimKind, strategy, ts, diff, setup, witness,
 * witnessSource, redTestScaffold.
 *
 * @param {object} defeat - Confirmed defeat with all fields
 * @param {string} [dir] - base dir (default '.')
 * @returns {string} path written
 */
export function writeReproArtifact(defeat, dir = '.') {
  const defeatsDir = join(dir, GATE_DEFEATS_DIR);
  mkdirSync(defeatsDir, { recursive: true });

  const artifact = {
    id: defeat.id ?? `cand-${Date.now()}`,
    target: defeat.target,
    claimKind: defeat.claimKind,
    strategy: defeat.strategy,
    ts: new Date().toISOString(),
    diff: defeat.diff,
    setup: defeat.setup ?? [],
    witness: defeat.witnessProposal,
    witnessSource: defeat.verdict?.witnessSource ?? defeat.witnessSource,
    redTestScaffold: buildRedTestScaffold(defeat),
  };

  const reproPath = join(defeatsDir, `${artifact.id}.json`);
  writeFileSync(reproPath, JSON.stringify(artifact, null, 2), 'utf8');
  return reproPath;
}

/**
 * Generate a RED test scaffold for the defeated gate.
 * This is a node:test stub that demonstrates the bypass against the target gate.
 *
 * @param {object} defeat
 * @returns {string} test scaffold source
 */
function buildRedTestScaffold(defeat) {
  const id = defeat.id ?? 'unknown';
  const target = defeat.target;
  const strategy = defeat.strategy ?? 'unknown';
  const claimKind = defeat.claimKind;

  return `// RED test scaffold — gate-fuzzing found bypass: ${id}
// Target: ${target} | Strategy: ${strategy} | Claim: ${claimKind}
// TODO: Move this to packages/${target}/test/bypass-${id}.test.mjs
// and make it PASS after fixing the gate.

import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join, tmpdir } from 'node:path';
import assert from 'node:assert/strict';

test('regression: gate-bypass ${id} (${strategy}) should now be caught', (t) => {
  // This test was auto-generated by gate-fuzzing.
  // Apply the bypass diff, run ${target}, verify it exits 2 (caught).
  // Before the fix, ${target} exits 0 (defeat). After the fix, it must exit 2.

  // TODO: Set up a git repo, apply this diff, run ${target}
  // Bypass diff summary: see .adlc/gate-defeats/${id}.json

  t.todo('Implement RED test from repro: .adlc/gate-defeats/${id}.json');
});
`;
}

/**
 * Append a cluster finding to .adlc/findings.jsonl (§4.4).
 * Uses plain prose desc with NO quoted/backticked literal so it routes to SPEC-GAP not LINT.
 *
 * @param {object} defeat
 * @param {string} reproPath - path to the repro artifact
 * @param {string} [dir] - base dir
 */
export function appendFinding(defeat, reproPath, dir = '.') {
  const adlcDir = join(dir, ADLC_DIR);
  // desc: plain prose, no quoted/backtick literal, no path in the desc itself
  // (routes to SPEC-GAP via lesson-foundry, not LINT — §4.4, F4)
  const desc = `gate-fuzzing defeated ${defeat.target} using ${defeat.strategy ?? 'unknown'} strategy, ` +
    `violating ${defeat.claimKind} property. ` +
    `Repro artifact at ${reproPath}`;

  const entry = {
    ts: new Date().toISOString(),
    tool: 'gate-fuzzing',
    file: `packages/${defeat.target}/bin/${defeat.target}.mjs`,
    line: 1,
    category: `gate-bypass:${defeat.strategy ?? 'unknown'}`,
    severity: 'high',
    desc,
    verdict: 'open',
    witnessSource: defeat.verdict?.witnessSource ?? defeat.witnessSource,
  };

  appendEntry('findings', entry, adlcDir);
  return entry;
}

/**
 * Record all defeats: write repro artifacts + append findings.
 * Only call with --record flag.
 *
 * @param {object[]} defeats
 * @param {string} [dir]
 * @returns {object[]} recorded entries with reproPath
 */
export function recordDefeats(defeats, dir = '.') {
  const recorded = [];
  for (const defeat of defeats) {
    const reproPath = writeReproArtifact(defeat, dir);
    const finding = appendFinding(defeat, reproPath, dir);
    recorded.push({ ...defeat, reproPath, finding });
  }
  return recorded;
}
