// lib/render.mjs — render premortem causes into markdown report.

/**
 * Render the parsed causes array into a markdown report.
 * @param {Array<{cause:string, earliest_signal:string, prevention:string, interrogation_question:string}>} causes
 * @returns {string}
 */
export function renderReport(causes) {
  const lines = [];

  lines.push('# Premortem Report');
  lines.push('');
  lines.push(
    '> Generated by `premortem`. The model was told this project already failed and asked to write the postmortem.'
  );
  lines.push('');
  lines.push('## Failure Causes');
  lines.push('');

  // Table header
  lines.push('| # | Cause | Earliest Signal | Prevention |');
  lines.push('|---|-------|-----------------|------------|');

  for (const [i, c] of causes.entries()) {
    const n = i + 1;
    const cause = escapeCell(c.cause ?? '');
    const signal = escapeCell(c.earliest_signal ?? '');
    const prevention = escapeCell(c.prevention ?? '');
    lines.push(`| ${n} | ${cause} | ${signal} | ${prevention} |`);
  }

  lines.push('');
  lines.push('## Questions to fold into interrogation');
  lines.push('');

  for (const [i, c] of causes.entries()) {
    const n = i + 1;
    lines.push(`${n}. ${c.interrogation_question ?? ''}`);
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Escape pipe characters inside table cells so markdown tables stay valid.
 * @param {string} text
 * @returns {string}
 */
function escapeCell(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
